name: Run pytest

on:
  push:
    branches: [main, feature/bioconda_package]
  pull_request:
    branches: [main]

jobs:
  pytest:
    name: Run pytest
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install .[test]
      - uses: pavelzw/pytest-action@v2
        env:
          ENA_WEBIN: ${{ secrets.ENA_WEBIN }}
          ENA_WEBIN_PASSWORD: ${{ secrets.ENA_WEBIN_PASSWORD }}
        with:
          emoji: false
          verbose: true
          job-summary: true
